### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by JorisPotier** [promeG/XLog#13]
Hi,

I tried to run your project but I think I missed something..
I cloned your repository, then use a simple `./gradlew :installExample`...
But when I launch the app on my connected device I can see log traces... but not those provided by `@XLog`.

Regards.

**Comment by promeG** [comment]
Hi,

XLog is based on [dexposed](https://github.com/alibaba/dexposed) framework. And on some devices XLog may not work due to dexposed's limitations.

Here is the current support status. Please check it.

| Runtime | Android Version | Support |
| --- | --- | --- |
| Dalvik | 2.2 | Not Test |
| Dalvik | 2.3 | Yes |
| Dalvik | 3.0 | No |
| Dalvik | 4.0-4.4 | Yes |
| ART | 5.0 | Testing |
| ART | 5.1 | No |

Regards.

**Comment by JorisPotier** [comment]
Hi,

I was testing with several Genymotions that are not supported obviously.

Thanks.
